/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as ConfigConfigureRouteImport } from './routes/$config/configure'
import { Route as ConfigManifestDotjsonRouteImport } from './routes/$config/manifest[.]json'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as StreamTypeIdRouteImport } from './routes/stream/$type/$id'
import { Route as ConfigStreamTypeIdRouteImport } from './routes/$config/stream/$type/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigConfigureRoute = ConfigConfigureRouteImport.update({
  id: '/$config/configure',
  path: '/$config/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigManifestDotjsonRoute = ConfigManifestDotjsonRouteImport.update({
  id: '/$config/manifest.json',
  path: '/$config/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamTypeIdRoute = StreamTypeIdRouteImport.update({
  id: '/stream/$type/$id',
  path: '/stream/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigStreamTypeIdRoute = ConfigStreamTypeIdRouteImport.update({
  id: '/$config/stream/$type/$id',
  path: '/$config/stream/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/$config/configure': typeof ConfigConfigureRoute
  '/$config/manifest.json': typeof ConfigManifestDotjsonRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/stream/$type/$id': typeof StreamTypeIdRoute
  '/$config/stream/$type/$id': typeof ConfigStreamTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/$config/configure': typeof ConfigConfigureRoute
  '/$config/manifest.json': typeof ConfigManifestDotjsonRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/stream/$type/$id': typeof StreamTypeIdRoute
  '/$config/stream/$type/$id': typeof ConfigStreamTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configure': typeof ConfigureRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/$config/configure': typeof ConfigConfigureRoute
  '/$config/manifest.json': typeof ConfigManifestDotjsonRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/stream/$type/$id': typeof StreamTypeIdRoute
  '/$config/stream/$type/$id': typeof ConfigStreamTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configure'
    | '/manifest.json'
    | '/$config/configure'
    | '/$config/manifest.json'
    | '/api/health'
    | '/api/search'
    | '/stream/$type/$id'
    | '/$config/stream/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configure'
    | '/manifest.json'
    | '/$config/configure'
    | '/$config/manifest.json'
    | '/api/health'
    | '/api/search'
    | '/stream/$type/$id'
    | '/$config/stream/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/configure'
    | '/manifest.json'
    | '/$config/configure'
    | '/$config/manifest.json'
    | '/api/health'
    | '/api/search'
    | '/stream/$type/$id'
    | '/$config/stream/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigureRoute: typeof ConfigureRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ConfigConfigureRoute: typeof ConfigConfigureRoute
  ConfigManifestDotjsonRoute: typeof ConfigManifestDotjsonRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  StreamTypeIdRoute: typeof StreamTypeIdRoute
  ConfigStreamTypeIdRoute: typeof ConfigStreamTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$config/configure': {
      id: '/$config/configure'
      path: '/$config/configure'
      fullPath: '/$config/configure'
      preLoaderRoute: typeof ConfigConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$config/manifest.json': {
      id: '/$config/manifest.json'
      path: '/$config/manifest.json'
      fullPath: '/$config/manifest.json'
      preLoaderRoute: typeof ConfigManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/$type/$id': {
      id: '/stream/$type/$id'
      path: '/stream/$type/$id'
      fullPath: '/stream/$type/$id'
      preLoaderRoute: typeof StreamTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$config/stream/$type/$id': {
      id: '/$config/stream/$type/$id'
      path: '/$config/stream/$type/$id'
      fullPath: '/$config/stream/$type/$id'
      preLoaderRoute: typeof ConfigStreamTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigureRoute: ConfigureRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ConfigConfigureRoute: ConfigConfigureRoute,
  ConfigManifestDotjsonRoute: ConfigManifestDotjsonRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  StreamTypeIdRoute: StreamTypeIdRoute,
  ConfigStreamTypeIdRoute: ConfigStreamTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
